spring:
  datasource:
    master:
      jdbc-url: jdbc:mysql://localhost:3306/fzt-boot?useSSL=false&useUnicode=true&characterEncoding=UTF-8
      username: root
      password: root
      driverClassName: com.mysql.jdbc.Driver
      type: com.alibaba.druid.pool.DruidDataSource
    cluster:
      jdbc-url: jdbc:mysql://localhost:3306/fzt-boot-cluster?useSSL=false&useUnicode=true&characterEncoding=UTF-8
      username: root
      password: root
      driverClassName: com.mysql.jdbc.Driver
      type: com.alibaba.druid.pool.DruidDataSource
  aop:
    auto: true
    proxy-target-class: true

mybatis:
  configuration:
    map-underscore-to-camel-case: true
  mapper-locations: classpath:mapping/*.xml
  type-aliases-package: com.fzt.boot.entity

pagehelper:
    helperDialect: mysql
    reasonable: true
    supportMethodsArguments: true
    params: count=countSql
    returnPageInfo: check

logging:
  level:
    com.fzt.boot.mapper: debug
