spring:
  datasource:
    druid:
      url: jdbc:mysql://localhost:3306/fzt-boot?useSSL=false&useUnicode=true&characterEncoding=UTF-8
      username: root
      password: root
      driver-class-name: com.mysql.jdbc.Driver

mybatis:
  configuration:
    map-underscore-to-camel-case: true
  mapper-locations: classpath:mapping/*.xml
  type-aliases-package: com.fzt.boot.entity

pagehelper:
    helperDialect: mysql
    reasonable: true
    supportMethodsArguments: true
    params: count=countSql
    returnPageInfo: check

logging:
  level:
    com.fzt.boot.mapper: debug
