spring:
  datasource:
    master:
      jdbc-url: jdbc:mysql://localhost:3306/fzt-boot?useSSL=false&useUnicode=true&characterEncoding=UTF-8
      username: root
      password: root
      driverClassName: com.mysql.jdbc.Driver
      type: com.alibaba.druid.pool.DruidDataSource
    cluster:
      jdbc-url: jdbc:mysql://localhost:3306/fzt-boot-cluster?useSSL=false&useUnicode=true&characterEncoding=UTF-8
      username: root
      password: root
      driverClassName: com.mysql.jdbc.Driver
      type: com.alibaba.druid.pool.DruidDataSource
  aop:
    auto: true
    proxy-target-class: true
  mail:
    host: # smtp.163.com  # smtp.qq.com
    username: # ****@163.com # ****@qq.com
    password: # **** # 是授权码不是登录密码
    to : # ****@qq.com # ****@163.com
  redis:
    host: localhost
    port: 6379
    database: 0
    lettuce:
      pool:
        max-active: 8
        min-idle: 0
        max-idle: 8
mybatis:
  configuration:
    map-underscore-to-camel-case: true
  mapper-locations: classpath:mapping/*.xml
  type-aliases-package: com.fzt.boot.entity

pagehelper:
    helperDialect: mysql
    reasonable: true
    supportMethodsArguments: true
    params: count=countSql
    returnPageInfo: check

logging:
  level:
    com.fzt.boot.mapper: debug
swagger:
  enabled: true #是否开启swagger
  title: fzt-boot
  version: 1.9.0.RELEASE
  base-package: com.fzt.boot.controller
  base-path: /**
#  更多配置参考文档：https://github.com/SpringForAll/spring-boot-starter-swagger

